[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "istanbul"
ffi = true
fs_permissions = [
  { access = "read", path = "./test/fixtures" },
  { access = "read-write", path = "./cache" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
